In [1]:
import torch
from probability_12 import p_w_new, p_pi_l_new, p_pi_r_new

In [2]:
index = (1,1)
tau = 1
beta = 1
var = 1
p = 10
x_l = torch.ones((10,3,3))
x_r = torch.zeros((10,3,3))
b = torch.zeros((10,3,3))
#pi_l = torch.zeros((10,3,3))
#pi_l[:,1,1] = 1
gamma = 1
pi_r = torch.zeros((10,3,3))
pi_r[:,1,1] = 1
w = 0.5*torch.ones((10,3,3))
w[:,0,1] = -0.5
p_pi_r_new(index,w,x_l,x_r,pi_r,var,b,tau,gamma,p)

tensor([0.0162, 0.0162, 0.0162, 0.0162, 0.0162, 0.0162, 0.0162, 0.0162, 0.0162,
        0.0162])

In [3]:
import numpy as np
np.exp(-4.125)

0.016163494588165874

In [12]:
_,ind = torch.sort(torch.rand(10))
print(ind)

tensor([6, 2, 5, 3, 7, 4, 1, 0, 9, 8])


In [15]:
torch.ones(2,2,2)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [3]:
from sampling_12 import simulation_new
import torch
device  = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
var,beta,gamma,alpha,tau,b,dim,p,no_sample = 0.001,10,10,0,1/100,torch.zeros((100,5,5)),5,100,1000,
s = simulation_new(var,beta,gamma,alpha,tau,b,dim,p,no_sample,device)

In [2]:
print(s)

tensor([[[[ 2.2403,  1.6653],
          [ 0.7294, -0.1239]],

         [[ 0.0990, -1.0354],
          [ 0.1622,  0.2678]],

         [[ 0.5010,  0.3047],
          [-0.0485, -0.2799]]],


        [[[ 2.2633, -0.4072],
          [ 1.4098, -0.1239]],

         [[-0.1396, -0.2312],
          [ 0.1622,  0.2678]],

         [[ 1.8482,  1.8186],
          [-0.0485, -0.2799]]],


        [[[-0.7367, -0.5553],
          [ 1.2459, -0.0881]],

         [[ 0.0161,  0.2331],
          [ 0.5611,  1.4615]],

         [[ 3.0797,  1.8186],
          [ 0.0910,  0.3441]]],


        [[[-2.3360, -0.8314],
          [ 2.6867, -0.1331]],

         [[ 0.0161, -0.4735],
          [-0.0141,  0.3984]],

         [[ 1.9283,  1.3188],
          [ 0.0910,  0.3441]]],


        [[[ 0.0556, -0.2798],
          [ 2.1845, -0.5119]],

         [[ 0.6817,  0.4796],
          [ 1.2047, -0.0575]],

         [[ 0.7779,  1.4149],
          [ 1.6688,  1.7148]]],


        [[[ 0.0556, -1.2489],
          [ 2.4890, -0.7692]],

In [2]:
from sampling_12 import simulation_new
from post_proccess import generate_hist
import torch
import numpy as np

'''var: noise variance for both eyes' evidence, equal'''
'''beta and gamma: coefficient on smoothness penalty of pi_l, pi_r and w'''
'''tau: a global coefficient on all penalty term'''
var,beta,gamma,alpha,tau,dim = 0.0001,10,10,0,1/100,5

'''change no parallel sequence and no. samples in each sequence here'''
p,no_sample = 100,2000
b = 0.5*torch.ones((p,dim,dim))

'''set device variable here'''
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")


s = simulation_new(var,beta,gamma,alpha,tau,b,dim,p,no_sample,device)

no_bins = 1000
cut_domi = 0

s.to('cpu')
s.numpy()
hist,bins = generate_hist(s,p,no_sample,no_bins,cut_domi)

'''output hist and bins variable to a csv file'''
import numpy.random as random
import numpy as np
rand_ind = random.randint(0,10000)
file_name_hist = 'hist'+str(rand_ind)
file_name_bins = 'bins'+str(rand_ind)
np.savetxt(file_name_hist, hist, delimiter=",")
np.savetxt(file_name_bins, bins, delimiter=",")